### ISSUE TITLE
PHP 5.6 requirement

### ISSUE THREAD

**Issue by cevou** [brick/geo#10]
Hi,

is there a reason, why the minimum requirement changed from 5.5 to 5.6? I had a quick lock at the recent changes and didn't find any usage of new features.
PErsonally, I think that the lib should not always use the latest PHP functionality, because you should be at least able to use this lib for example with the latest Ubuntu LTS release.

Best,
Christoph

**Comment by BenMorel** [comment]
Hi Christoph,

The constructors have been made public, and implemented using varadics, which are a PHP 5.6 feature:
https://github.com/brick/geo/blob/master/src/LineString.php#L41

This made much more sense overall than the previous implementation. I reckon that an equivalent functionality could be achieved with PHP 5.5 syntax, but it would be a bit uglier; I prefer moving forward with new PHP releases rather than focusing on old releases, at least while I can (when this library will be officially released with version numbers, BC will be much more of a preoccupation).

Note than even on LTS releases, there are community-supported repositories available to install PHP 5.6, see for example:
http://www.dev-metal.com/install-setup-php-5-6-ubuntu-14-04-lts/
