### ISSUE TITLE
as binary return 0 srid

### ISSUE THREAD

**Issue by quizact** [brick/geo#28]
Great extension,

I have an issue here, I need to insert the wkb geometry to database. when I used asbinary function, the query return 0 srid. When I check used srid function, the query return 4326. How can I solved this issue? Here you are the code

$encodejson = $request->coordinates[$i];
 $readgeojson = new GeoJSONReader();
 $geom = $readgeojson->read($encodejson);
  $geom2 = bin2hex($geom->asBinary());

**Comment by BenMorel** [comment]
Hi, WKB does not store the SRID. It's a known limitation of the format. That's why [WKBReader::read()](https://github.com/brick/geo/blob/3a9104c0ca7cfe4c85aab83671fd1384509baca9/src/IO/WKBReader.php#L22) accepts a `$srid` parameter:

```php
public function read(string $wkb, int $srid = 0) : Geometry
```

If you want the geometry AND the SRID to be stored in binary form, you can use EWKB, but it's PostGIS-specific.
