### ISSUE TITLE
Distance function result differ between engines

### ISSUE THREAD

**Issue by nono303** [brick/geo#29]
Salut @BenMorel,

I’m currently looking for performance and accuracy methods in distance calculation between two 4326 (lat/lon) points and I’ve noticed that unit return depends on engine:
```
	$latf = 45.832615;
	$lonf = 6.865129;
	$latt = 44.922525;
	$lont = 6.359967;
	echo (Point::fromText('POINT ('.$latf.' '.$lonf.')', 4326))->distance(Point::fromText('POINT ('.$latt.' '.$lont.')', 4326));
```

- `GeometryEngineRegistry::set(new PDOEngine($pdo));` return a **distance in meters**
- `GeometryEngineRegistry::set(new GEOSEngine());` return **an angle**

Same result when using php-geos with geos engine enable and pure MySQL request.
```
c:\php>php calcul_distance.php

# methode                      | time     | meters
------------------------------ | -------- | ----------
haversineGreatCircleDistance   | 5.95     | 108616.75
vincentyGreatCircleDistance    | 8.4      | 108616.75
phpGeosDistanceLatLon          | 248.9    | 1.04
phpGeosHausdorffDistanceLatLon | 245.58   | 1.04
brickGeosDistanceLatLon        | 209.67   | 1.04
brickMySQLDistanceLatLon       | 2970.37  | 108610.81
MySQLDistanceLatLon            | 2464.14  | 108610.81
```
Does I missed something in my wkt Point definition?
If not, does these different results (because it’s not an issue) seems for you normal ?

++NoNo

**Comment by BenMorel** [comment]
Hi, it's not really an issue but a difference in implementation between different geometry engines. Here is the current state of things, if I'm not mistaken:

- MySQL returns all calculations in meters when using SRID 4326
- MariaDB returns all calculations in degrees
- GEOS returns all calculations in degrees
- PostGIS requires to use the `Geography` type instead of `Geometry`, or to pass a flag to GIS functions, to return in meters
- Not sure about SQLite.

In your case, I would advise you to use the `PDOEngine` with MySQL if you want the result in meters!

**Comment by nono303** [comment]
Thx @BenMorel for these precision!
I'll keep my "pure php" `haversineGreatCircleDistance` function as it's more than 400x faster than PDOEngine ^^

**Comment by BenMorel** [comment]
Hi, could you please share the code of your `haversineGreatCircleDistance` and `vincentyGreatCircleDistance` functions should other people need them? And explain the differences between them?

Regarding your benchmark, I'd be interested to know the more about it: how many iterations? Is time in milliseconds?

You should also re-run it using `Point::xy($lat, $lon, 4326)` instead of `Point::fromText('POINT ('.$latf.' '.$lonf.')', 4326)`, otherwise you're spending a lot of time parsing the WKT when a factory method can do the job much faster.

Anyway, it will still probably be much slower due to the need to encode the data to WKB to send to the DB, and the database round-trip, which involves a TCP or socket connection, parsing the SQL query at DB level, etc. But maybe a lot less than when instantiating Points using WKT.

**Comment by nono303** [comment]
Hi @BenMorel 
Just updated brick* func with Point::xy
```
>>>>>> testDistance(45.832615, 6.865129,44.922525, 6.359967))
* 10000 iterations             | ms       | m or °
haversineGreatCircleDistance   | 10       | 108373.84
vincentyGreatCircleDistance    | 13       | 108373.84
phpGeosDistanceLatLon          | 543.579  | 1.04
phpGeosHausdorffDistanceLatLon | 518.604  | 1.04
brickGeosDistanceLatLon        | 176.516  | 1.04
brickMySQLDistanceLatLon       | 1736.168 | 108610.81
MySQLDistanceLatLon            | 1516.732 | 108610.81
```
script attached with explanation links in comments for methods.

[calcul_distance.php](https://github.com/brick/geo/files/6254304/calcul_distance.php.txt)

**Comment by BenMorel** [comment]
Thank you, I'm attaching the formulas here for posterity:

```php
define('EARTHRADIUS', 6356752.3142);

// https://en.wikipedia.org/wiki/Vincenty%27s_formulae
function vincentyGreatCircleDistance($latFrom, $lonFrom, $latTo, $lonTo, $earthRadius = EARTHRADIUS)
{
    $latFrom = deg2rad($latFrom);
    $lonFrom = deg2rad($lonFrom);
    $latTo   = deg2rad($latTo);
    $lonTo   = deg2rad($lonTo);

    $lonDelta = $lonTo - $lonFrom;

    $a = pow(cos($latTo) * sin($lonDelta), 2)
        + pow(cos($latFrom) * sin($latTo) - sin($latFrom) * cos($latTo) * cos($lonDelta), 2);
    $b = sin($latFrom) * sin($latTo) + cos($latFrom) * cos($latTo) * cos($lonDelta);

    $angle = atan2(sqrt($a), $b);
    return $angle * $earthRadius;
}

// https://en.wikipedia.org/wiki/Haversine_formula
function haversineGreatCircleDistance($latFrom, $lonFrom, $latTo, $lonTo, $earthRadius = EARTHRADIUS)
{
    $latFrom = deg2rad($latFrom);
    $lonFrom = deg2rad($lonFrom);
    $latTo   = deg2rad($latTo);
    $lonTo   = deg2rad($lonTo);

    $latDelta = $latTo - $latFrom;
    $lonDelta = $lonTo - $lonFrom;

    $angle = 2 * asin(sqrt(pow(sin($latDelta / 2), 2)
        + cos($latFrom) * cos($latTo) * pow(sin($lonDelta / 2), 2)));

    return $angle * $earthRadius;
}
```

Regarding your benchmarks, as you've discovered, there's a rather large overhead in issuing a SQL query to perform a calculation. That being said, I'm happy to see that the overhead of brick/geo itself is minimal (+14%) compared to issuing a raw SQL query. And by using this library, you get the benefit of strongly typed objects instead of relying on raw coordinates, and a nice abstraction above the underlying geometry engine (MySQL, GEOS, etc.)

That being said, it's also important put things into perspective: even with the relative slowness of a SQL query, you're still able to achieve ~4000 distance calculations per second, plus you're not limited to distance calculations between 2 points: you can perform distance calculations between polygons, and much, much more, for a total performance cost that will be in the same order of magnitude as a simple distance calculation between 2 points.

But if what you're looking for is raw performance for a distance between 2 points on the spheroid, then by all means, use the functions above :+1:

**Comment by nono303** [comment]
...and note that with [geos](https://github.com/libgeos/geos) engine, **[brick/geo](https://github.com/brick/geo) it 3 time faster** than [geoPHP](https://github.com/phayes/geoPHP) witch itself use [php-geos](https://github.com/ModelTech/php-geos) extension ;)
